### ISSUE TITLE
Checksum of installer package

### ISSUE THREAD

**Issue by yangwao** [github/SoftU2F#11]
As this is security product, where people will store their codes, would be highly recommended to show checksum of package.
I just downloaded this package. 
```
3265818 Jul 25 15:56 SoftU2F.pkg
⫸  shasum -a 512 SoftU2F.pkg
3e626b7eaa6895e89198ce1a3840d925fe69629fd909adbde0018491d4d87b4709283845a446b7fbdeec41992c36461fdf3860e43759241d7b05cea475d2f14a  SoftU2F.pkg
```
However, how do I know what is proper checksum of package?

**Comment by btoews** [comment]
I rebuilt and reuploaded [v0.0.8](https://github.com/github/SoftU2F/releases/tag/0.0.8) and added a checksum to the release description.
