### ISSUE TITLE
Firefox support (which extension?)

### ISSUE THREAD

**Issue by stephenyeargin** [github/SoftU2F#15]
So, I have this working great with Chrome 👍 

But I cannot seem to get it working with what I presume is the [Firefox extension](https://addons.mozilla.org/en-US/firefox/addon/u2f-support-add-on/) mentioned in the README. Anyone had any luck with it?

**Comment by btoews** [comment]
Thanks for opening this. This should be fixed in [v0.0.10](https://github.com/github/SoftU2F/releases/tag/0.0.10). To upgrade, just download/run the new installer. Let me know if this doesn't work.

**Comment by stephenyeargin** [comment]
👍 Confirmed it's working with macOS 10.12, but not having as much success with the 10.13 beta (for either browser) on my home computer. That's unrelated to this, however. I'll look into messing with that later tonight.

**Comment by btoews** [comment]
Yeah. I just installed High Sierra also and am having problems too. I was about to open an issue, since I'm not sure on the fix yet and someone else might have an idea.

**Comment by yoyo930021** [comment]
I find a config in firefox nightly.
`security.webauth.u2f` and `security.webauth.u2f_enable_softtoken`
All turn to true.
 In demo page, It's work. but not have notification.

**Comment by btoews** [comment]
Firefox has its own internal software U2F implementation, though that is just intended for testing while they add HID support. That is what those config flags enable. If you want to use Soft U2F or any hardware U2F device with Firefox you'll need to install [this extension](https://addons.mozilla.org/en-US/firefox/addon/u2f-support-add-on/) for the time being.

**Comment by tommythorn** [comment]
Alas the extension mentioned above isn't compatible with Firefox Quantum (61.0) so is there another workaround?

**Comment by btoews** [comment]
I'm not aware of any workaround for using U2F in FF without that extension.

**Comment by tubbo** [comment]
@tommythorn @mastahyeti [Firefox Quantum includes native U2F support](https://www.yubico.com/2017/11/how-to-navigate-fido-u2f-in-firefox-quantum/), but according to that article, Mozilla didn't fully implement the FIDO AppID and Facet specification. Perhaps that's why I get the following error from the [Yubico Demo Site](https://demo.yubico.com/) when I try to register Firefox Quantum (63.0b13) as a device:

```
 Traceback (most recent call last):
  File "/root/python-u2flib-server-demo/examples/yubiauth_server.py", line 161, in __call__
    raise Exception("FIDO Client error: %s" % error)
Exception: FIDO Client error: 1 (OTHER ERROR)
```
