### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by homakov** [github/SoftU2F#17]
It wasn't immediately clear to me how can i handle backups and recovery? Is it already in keychain so I don't need to worry? Are there plans to use same token on eg iOS?

**Comment by yackermann** [comment]
@homakov U2F was designed to register unique key-pair on every-single registration. Backups should not be a thing.

**Comment by yackermann** [comment]
New token, new registration. Keys are intended to be irrecoverable.

**Comment by yackermann** [comment]
@homakov FYI: Protocol overview https://habrahabr.ru/post/305508/

**Comment by yackermann** [comment]
Would be nice to default all the crypto to Secure Enclave if such available.

**Comment by homakov** [comment]
Really? I signed up with this soft app, lost my device, what's next? How to login same account again?

**Comment by yackermann** [comment]
@homakov You have multiple tokens/u2f devices registered. If there is a way to recover your private keys, adversary can easily clone your token and get access to your account. 

U2F designed such way that device can not leaked private info about user. Yubico does it with key wrapping, so no actual private key stored on the device, only master key that then used to unwrap Pk from keyhandle. Other vendors use secure enclaves to store keys in SecureDB.

Apple with their TouchID and ApplePay does exactly the same. 

No key should be ever leaked.

**Comment by yackermann** [comment]
P.S. Watch this https://www.youtube.com/watch?v=7UNeUT_sRos

**Comment by homakov** [comment]
So the answer is I'm supposed to register 2+ tokens? And what would be my 2nd token if I only have this app? What if I lose both? How many tokens should I have added to **all** accounts, like 5 or what?

No worries, I already know how wrapping works as well as protocol spec. I was talking about master key aka device secret.

**Comment by yackermann** [comment]
@homakov Think about U2F as your house keys. You don't have one key, you have backups. Your partner, your stash, etc. So we generally suggest to have at lest two tokens. My friends generally have one token on their keys, and one under their tomatoes in the tin can(i.e. in safe at home).

Another thing is of-course to setup account recovery with recovery OTP or the way that facebook and github does now, with Delegated-Recovery.

Personally I have three tokens in use.

**Comment by homakov** [comment]
It's a pity this vision of "house keys" is only allowed and "official" approach. I __hate__ traditional house keys and can't wait for things like Lockitron to take off. On top of that I always travel, and have no long term "safe place". A lot of my friends live like that too.

Recovery OTP sounds equivalent to master seed since you can replace it with new token. I never noticed it - is it required by protocol to offer them?

Delegated recovery is basically giving access to your account to 3rd party, diminishing very idea of u2f.

If only U2F stopped this "never recover" and "everyone must use hardware" nonsense, it would be such an amazing protocol I could support.

**Comment by yackermann** [comment]
You either have shared secret like password, or backed-up private keys that can compromise you, or you have hardware-backed irrecoverable crypto, that can not compromise you.

All secure authentication inevitably will be hardware backed and so irrecoverable. Credit cards, Apple Pay, Android Pay, RSA Tokens, U2F Tokes, TEE, TPM, SGX all hardware based, and more and more devices have Secure Enclave in them.

The only secret we can't leak is the one we don't know.

If you are arguing case of usability of U2F tokens and wan't something more mobile base, read about WebAuthn http://slides.com/herrjemand/webauthn-isig#/

**Comment by homakov** [comment]
By hardware I mean one you need to buy, if it goes built in like SEP - that's great. 

>You either have shared secret like password, or backed-up private keys that can compromise you

Not true. Password derived key can be injected in hardware in write only mode, then cannot be leaked. It's best of both worlds, no?

>If you are arguing case of usability of U2F tokens and wan't something more mobile base

**everyone** wants something more mobile base

**Comment by yackermann** [comment]
> everyone wants something more mobile base

We are working hard on it.*)

> Not true. Password derived key can be injected in hardware in write only mode, then cannot be leaked. It's best of both worlds, no?

It's still has security level of the password, as you can recover Pk by bruteforcing password.

The only secure Pk, is the one that you don't know

For now U2F is the best 2FA we have(jup, I know I work for FIDO, but it's the fact). U2F Tokens are not that expensive and go as low as few 8$(search amazon). 

So: We are working on something more mobile based, and we are very close, but for now U2F is the best 2FA we have, so it's a good thing to get.

**Comment by homakov** [comment]
>It's still has security level of the password, as you can recover Pk by bruteforcing password.

Common mistake, strength depends entirely on derivation scheme and some schemes are too expensive to break (been proven in the wild with bounties up to 20 BTC and 8 char passwords). 

>The only secure Pk, is the one that you don't know

Security out of touch with usability isn't going far, not using computers at all is even more secure and you can't argue with that.

It might be best, but it's definitely not good enough.

**Comment by yackermann** [comment]
> It might be best, but it's definitely not good enough.

We are working to make it better. 

> Common mistake, strength depends entirely on derivation scheme and some schemes are too expensive to break (been proven in the wild with bounties up to 20 BTC and 8 char passwords).

They are based on Seed encryption. password[seed -> key]. Still easy to break if encrypted see acquired

**Comment by homakov** [comment]
I was talking about https://keybase.io/warp/warp_1.0.9_SHA256_a2067491ab582bde779f4505055807c2479354633a2216b22cf1e92d1a6e4a87.html - does it sound good?

it's true that encrypted seed is usally easier to brute when acquired. Usually it is <1 sec to decrypt on consumer devices, while warpwallet is anywhere 10-100 seconds ie 100 times stronger. My belief is it's very good tradeoff of usability and strength. 

And I see no reason for u2f or anyone to dictate against using it, ie it can be left up to implementation, why not?

**Comment by yackermann** [comment]
U2F does not dictates how you generate keypairs.

However, I would like to point out is that this example takes 10 sec to generate keypair, U2F required to do it under 500ms. Usability clearly fails in the example.

**Comment by homakov** [comment]
so if someone invests time in pw  approach it still would be compliant? i wish it was explicitely allowed in spec.

it takes 10s once for master seed derivation, after setup it is instant to use.

**Comment by yackermann** [comment]
@homakov Yes, technically you can make password based u2f token. You can use password as user verification method.

**Comment by btoews** [comment]
@homakov To answer your original question, Soft U2F currently stores key material in the macOS Keychain. I haven't put any effort into figuring out how to export/backup those keys. If you figure it out, a PR to update the `README.md` would be welcome.
