### ISSUE TITLE
Doesn't work on Sierra

### ISSUE THREAD

**Issue by akaralar** [github/SoftU2F#18]
I'm using macOS 10.12.6

I installed the app and it installed without problems. After installation, when I fire up the program, it shuts down and exits immediately.

I'll be happy to provide more info, but don't know how.

**Comment by btoews** [comment]
> I installed the app and it installed without problems. After installation, when I fire up the program, it shuts down and exits immediately.

The app runs as a launchd agent, so you shouldn't have to launch it manually. Also, there is no UI component to the app, so it might have been running in the background already. Have you tried using it with a U2F-enabled site (Eg. https://demo.yubico.com/u2f?tab=register)? If not, please try that. Otherwise, here are some details that would be helpful for debugging:

1. Does `/Library/Extensions/softu2f.kext` exist?
1. Does `~/Library/LaunchAgents/com.github.SoftU2F.plist` exist?
1. What is the output of `ps aux | grep -i softu2f`?
1. What is the output of `sudo kextstat -b com.github.SoftU2FDriver`?

**Comment by iCyberon** [comment]
Same issue.

1. Yes
2. Yes
3. `cyberon           4782   0.0  0.2  4352572  14992   ??  S     8:52PM   0:00.11 /Applications/SoftU2F.app/Contents/MacOS/SoftU2F`
4. `  190    0 0xffffff7f85c5a000 0x5000     0x5000     com.github.SoftU2FDriver (1) D06D7D01-01BB-3049-8DD6-0D9F4C0A7562 <45 5 4 3>`

Looks like everything is installed correctly.

**Comment by btoews** [comment]
It seems like launching the `SoftU2F.app` manually might mess with the instance that's already running. Did you do this also @iCyberon? I should figure out what's actually going on and fix it, but in the meantime, you might be able to get things working by running

- `launchctl unload ~/Library/LaunchAgents/com.github.SoftU2F.plist`
- `launchctl load ~/Library/LaunchAgents/com.github.SoftU2F.plist`

to stop/restart the launchd agent.

**Comment by manuelmeurer** [comment]
I just installed SoftU2F via Homebrew Cask and I can't get it to show up on the Yubico Demo Site either.
My answers to your questions:
1. Yes
2. Yes
3.
```
manuel           72918   0.0  0.0  2442020    820 s005  S+    3:57PM   0:00.00 grep -i softu2f
root             71697   0.0  0.1  2558828  10064   ??  Ss    3:49PM   0:00.35 /Applications/SoftU2F.app/Contents/MacOS/SoftU2F
```
4.
```
Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
  307    0 0xffffff7f83af7000 0x5000     0x5000     com.github.SoftU2FDriver (1) D06D7D01-01BB-3049-8DD6-0D9F4C0A7562 <38 5 4 3>
```

Restarting the launch agent or Chrome didn't fix it either.

**Comment by btoews** [comment]
@manuelmeurer Hmm. I didn't know that Soft U2F had been added to homebrew. Can you try unloading the launchd agent, running the app manually, and seeing what output is generated when trying the Yubico demo?

1. `launchctl unload ~/Library/LaunchAgents/com.github.SoftU2F.plist`
1. `/Applications/SoftU2F.app/Contents/MacOS/SoftU2F`

**Comment by manuelmeurer** [comment]
It seems like `~/Library/LaunchAgents/com.github.SoftU2F.plist` was not loaded:

```
$ sudo launchctl unload ~/Library/LaunchAgents/com.github.SoftU2F.plist 
/Users/manuel/Library/LaunchAgents/com.github.SoftU2F.plist: Could not find specified service
```

Launching the app produced:
```
$ /Applications/SoftU2F.app/Contents/MacOS/SoftU2F
Starting U2FHID thread
U2FHID thread started
Starting softu2f async run loop.
```

But the Yubico demo still doesn't work.

Just to make sure I'm doing the right thing: on https://demo.yubico.com/u2f?tab=register I enter a username and password, and when the "Performing U2F action" modal comes up, I should get a Chrome notification from SoftU2F, right?

**Comment by btoews** [comment]
> Just to make sure I'm doing the right thing: on https://demo.yubico.com/u2f?tab=register I enter a username and password, and when the "Performing U2F action" modal comes up, I should get a Chrome notification from SoftU2F, right?

Correct.

Did you see any further output in the console where the app was running when you tried the Yubico demo?

**Comment by manuelmeurer** [comment]
Nope... :(

**Comment by btoews** [comment]
I can't get the homebrew install to work at all, but you seem to have gotten further with it than I did. I'm unsure of whether your issue has to do with how Soft U2F installs via homebrew of with Soft U2F itself. Can you try uninstalling the homebrew version and installing the `.pkg` from the [releases page](https://github.com/github/softU2F/releases/latest). That'll at least help isolate the problem.

**Comment by manuelmeurer** [comment]
This is how the install via Homebrew Cask worked for me:

```
$ brew cask install softu2f
==> Satisfying dependencies
==> Downloading https://github.com/github/SoftU2F/releases/download/0.0.12/SoftU2F.pkg
######################################################################## 100.0%
==> Verifying checksum for Cask softu2f
==> Installing Cask softu2f
==> Running installer for softu2f; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> installer: Package name is SoftU2F
==> installer: Installing at base path /
==> installer: The install was successful.
🍺  softu2f was successfully installed!
```

I uninstalled it via Homebrew Cask and installed the PKG, but the result was the same, no SoftU2F popup on the Yubico website.
So I started deactivating one Chrome extension after the other and finally it worked! The culprit is... (drumroll)... 1Password. Each time I submitted the registration form on the Yubico website, I got a popup from 1Password asking me if I want to save that login. No matter what I choose, the SoftU2F popup doesn't appear. When I deactivated the 1Password extension, it does.

Any idea why those two won't work together?

**Comment by manuelmeurer** [comment]
Unrelated, but how do I actually use SoftU2F with GitHub.com? I assume I have to configure it somewhere on this page? https://github.com/settings/two_factor_authentication/configure

**Comment by btoews** [comment]
> Any idea why those two won't work together?

I've seen similar behavior before. Chrome doesn't try to do the HID U2F operation if the tab requesting the U2F operation loses focus. My bet would be that the extension would cause problems with a hardware U2F device also. It may be worth opening a Chrome issue about that. I can take care of that if you prefer.

> Unrelated, but how do I actually use SoftU2F with GitHub.com? I assume I have to configure it somewhere on this page? https://github.com/settings/two_factor_authentication/configure

Yep. At the bottom of that page, you should see a `Security keys` section. Click <kbd>Register new device</kbd>, give it a name, and press <kbd>Add</kbd>. You should then see a Soft U2F prompt, telling you that GitHub.com is trying to register. Click <kbd>Allow</kbd> and you should be all setup.

**Comment by manuelmeurer** [comment]
Yes, please go ahead and open the Chrome issue. I'm sure you can explain the problem much better. 😸 

And thanks for pointing out I have to register a new device! Worked flawlessly.

**Comment by btoews** [comment]
I opened a bug [here](https://bugs.chromium.org/p/chromium/issues/detail?id=750294). Given the discussion in [this other bug](https://bugs.chromium.org/p/chromium/issues/detail?id=451165), I'm guessing they wont change the current behavior.

**Comment by btoews** [comment]
@akaralar I'm sorry this thread has gotten hijacked a few times. Are you still having issues getting Soft U2F to work? If not, I'd like to close this out.

**Comment by grempe** [comment]
I encountered the same issue with the Yubico demo page. On a hunch, I disabled the 1password extension in Chrome (it was popping up an alert wanting to know if I wanted to remember reg info about the Yubico demo page). Once I did that and reloaded the page it seemed to work and allowed me to reg and login on the Yubico demo.

1Password extension v4.6.8.90, Chrome Version 60.0.3112.78 (Official Build) beta (64-bit)

**Comment by akaralar** [comment]
@mastahyeti Yeah sorry I thought Safari supported it, tried it with Chrome and it's working. But at least a menubar icon would be nice, I might want to have a way to shut this down other than activity monitor while I'm not at my computer.

Thanks!

**Comment by btoews** [comment]
Cool! I definitely agree that adding some form of UI to this app would be useful.

**Comment by metabaron** [comment]
I can confirm that disabling the 1password extension solve it all for me too
