### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by mu-arch** [github/SoftU2F#22]
Opening another issue because the former one was prematurely closed. I am still having the install failed issue on version 0.0.11 on OS X 10.12.6 (16G29).

<img width="632" alt="28551636-e2298b38-70ae-11e7-89d2-22aa53d73273" src="https://user-images.githubusercontent.com/6717350/28642432-03fe5b70-7218-11e7-9f8d-48fd0010b6be.png">

>Does /Library/Extensions/softu2f.kext exist?
>Does ~/Library/LaunchAgents/com.github.SoftU2F.plist exist?
>What is the output of ps aux | grep -i softu2f?
>What is the output of sudo kextstat -b com.github.SoftU2FDriver?

1. Yes
2. Yes
3. daves            2167   0.0  0.0  2442020   1944 s000  S+    3:32PM   0:00.00 grep -I softu2f
4. Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
  146    0 0xffffff7f82374000 0x5000     0x5000     com.github.SoftU2FDriver (1) D06D7D01-01BB-3049-8DD6-0D9F4C0A7562 <34 5 4 3>

**Comment by btoews** [comment]
> Opening another issue because the former one was prematurely closed

Whoops. Sorry about that. Can you share the relevant contents from `/var/log/install.log`? Maybe the past day's worth of logs if you aren't sure what' relevant. We can email if you aren't comfortable posting logs in a public issue.

**Comment by mu-arch** [comment]
`Jul 26 16:13:17 Mac installd[309]: PackageKit: kextcache -system-caches
Jul 26 16:13:17 Mac installd[309]: PackageKit: kextcache -update-volume / -Installer
Jul 26 16:13:20 Mac installd[309]: kextcache: Untrusted kexts are not allowed
Jul 26 16:13:20 Mac installd[309]: kextcache: AppleMobileDevice.kext has invalid signature; omitting.
Jul 26 16:13:32 Mac installd[309]: kextcache: KernelCache ID: 908F3EBE234BFC0304716358161801CF
Jul 26 16:13:32 Mac installd[309]: PackageKit: Executing script "./postinstall" in /private/tmp/PKInstallSandbox.sbYimC/Scripts/com.GitHub.SoftU2F.fK0qXJ
Jul 26 16:13:33 Mac installd[309]: ./postinstall: /tmp/PKInstallSandbox.sbYimC/Scripts/com.GitHub.SoftU2F.fK0qXJ/postinstall: line 11: /Users/daves/Library/LaunchAgents/com.github.SoftU2F.plist: No such file or directory
Jul 26 16:13:33 Mac install_monitor[2241]: Re-included: /Applications, /Library, /System, /bin, /private, /sbin, /usr
Jul 26 16:13:33 Mac installd[309]: PackageKit: releasing backupd
Jul 26 16:13:33 Mac installd[309]: PackageKit: allow user idle system sleep
Jul 26 16:13:33 Mac installd[309]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “SoftU2F.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Users/daves/Downloads/SoftU2F.pkg, PKInstallPackageIdentifier=com.GitHub.SoftU2F, NSLocalizedDescription=An error occurred while running scripts from the package “SoftU2F.pkg”.} {
	    NSFilePath = "./postinstall";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201cSoftU2F.pkg\U201d.";
	    NSURL = "file://localhost/Users/daves/Downloads/SoftU2F.pkg";
	    PKInstallPackageIdentifier = "com.GitHub.SoftU2F";
	}
Jul 26 16:13:33 Mac installd[309]: PackageKit: Running idle tasks
Jul 26 16:13:33 Mac Installer[2232]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “SoftU2F.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Users/daves/Downloads/SoftU2F.pkg, PKInstallPackageIdentifier=com.GitHub.SoftU2F, NSLocalizedDescription=An error occurred while running scripts from the package “SoftU2F.pkg”.}`

These appear to be the relevant logs. I noticed the part about disabled kexts so I tried the install with gatekeeper disabled but it did not solve the issue.

**Comment by btoews** [comment]
Thanks. The interesting part here is

```
Jul 26 16:13:33 Mac installd[309]: ./postinstall: /tmp/PKInstallSandbox.sbYimC/Scripts/com.GitHub.SoftU2F.fK0qXJ/postinstall: line 11: /Users/daves/Library/LaunchAgents/com.github.SoftU2F.plist: No such file or directory 
```

Just to confirm. Your username on this computer is `daves` and the `/Users/daves/Library/LaunchAgents/com.github.SoftU2F.plist` file *does* exist?

**Comment by mu-arch** [comment]
Oddly when I tried earlier it did exist but after my most recent install it currently does not exist. So as of now, no, that file does not exist.

I'm not sure what is the username on OS X, davesis what appears in the terminal but my full real name appears as the username blank when OS X asks me to authenticate via GUI.

**Comment by btoews** [comment]
Ok. Line 11 of the postinstall script is actually the one that makes that file, so maybe the directory doesn't exist? The `/Users/daves/Library/LaunchAgents/` directory exists right now?

**Comment by mu-arch** [comment]
No that dir doesn't exist either.

Take note of the edit I made to my previous post regarding usernames.

**Comment by btoews** [comment]
That's bizarre. Going up the chain,

- Does `/Users/daves/Library/` exist?
- Does `/Users/daves/` exist?

**Comment by mu-arch** [comment]
`/Users/daves/Library/` exists. This is very odd though because these were getting created when I checked previously.

**Comment by btoews** [comment]
Would you mind making that directory and trying the installer again?

```
mkdir -p /Users/daves/Library/LaunchAgents/
```

That's a system directory, that I think should exist on a fresh macOS install. I'm not sure why it would be missing.

**Comment by mu-arch** [comment]
Wow, it worked that time. I must have made a mistake earlier when I checked if that dir existed. I apologize for that.

Very odd that wasn't created by the OS though? I'm actually running a clean install of OS X with only the OS updates applied and Xcode installed.

**Comment by btoews** [comment]
@sukoonmusic helped me confirm that this directory will be present on a fresh install. I'm going to close this issue now. If other folks have problems with this we can add a `mkdir -p ~/Library/LaunchAgents/` to the postinstall script.
