### ISSUE TITLE
Any plans to support Linux?

### ISSUE THREAD

**Issue by hilyin** [github/SoftU2F#23]

**Comment by yackermann** [comment]
@hilyin This project is a Swift OSX project that relies on OSX notification service... so no.

**Comment by yackermann** [comment]
You can use FooHID to create virtual u2f hid token https://github.com/unbit/foohid and bind some notification gui to that

**Comment by btoews** [comment]
@hilyin Sadly, no.

> You can use FooHID to create virtual u2f hid token https://github.com/unbit/foohid and bind some notification gui to that

FooHID is also macOS only.

**Comment by yackermann** [comment]
@mastahyeti thanks for pointing that out, I meant USBBIP-VUSB https://github.com/lcgamboa/USBIP-Virtual-USB-Device

**Comment by btoews** [comment]
I'm closing this, since it doesn't represent a bug/issue in Soft U2F. Feel free to keep the conversation going of how to reimplement Soft U2F for Linux though.

**Comment by 0x326** [comment]
@mastahyeti Would the [Silver](https://www.elementscompiler.com/elements/silver/default.aspx) project aid in targeting Linux?

**Comment by btoews** [comment]
That might allow for some code reuse, but it would still be a major effort to port this to another OS.

**Comment by normanr** [comment]
See https://github.com/danstiner/rust-u2f as an alternative for Linux.
