### ISSUE TITLE
Document the correct Safari extension.

### ISSUE THREAD

**Issue by davidchisnall** [github/SoftU2F#33]
The README.md file states that this works:
> with the U2F extensions for OS X Safari and Firefox

The only U2F extension for Safari that shows up in searches (with DuckDuckGo, Bing or Google) is Safari-FIDO-U2F/Safari-FIDO-U2F, but this has an open issue Safari-FIDO-U2F/Safari-FIDO-U2F#19 saying that it doesn't work with this project.  Please document the extensions with which this has been tested.

**Comment by btoews** [comment]
I assume https://github.com/Safari-FIDO-U2F/Safari-FIDO-U2F/issues/19 was the same issue as https://github.com/github/SoftU2F/issues/15, which was then fixed in https://github.com/github/SoftU2F/pull/16. Have you tested the Safari extension with a recent build of Soft U2F?

**Comment by davidchisnall** [comment]
I hadn't tested, but now have.  Going to the demo page, I get this error when I attempt to register:
```
 Traceback (most recent call last):
  File "/root/python-u2flib-server-demo/examples/yubiauth_server.py", line 167, in __call__
    ret = self.bind(username, password, data)
  File "/root/python-u2flib-server-demo/examples/yubiauth_server.py", line 193, in bind
    user = self._get_user(username, password)
  File "/root/python-u2flib-server-demo/examples/yubiauth_server.py", line 233, in _get_user
    user = self.auth.get_user(username)
  File "/usr/lib/python2.7/dist-packages/yubiauth/core/controller.py", line 161, in get_user
    raise LookupError('User not found!')
LookupError: User not found!
```
The pop-up thing appears and asks me to accept or reject.  I've tried a couple of times, with random usernames, hitting accept each time and I get the same error each time.

**Comment by btoews** [comment]
This seems to be a bug in the Yubico site. I'm getting the same error in Chrome with a Yubikey device.

**Comment by btoews** [comment]
I tested on GitHub and the extension works fine with Soft U2F on GitHub.

**Comment by davidchisnall** [comment]
Thanks.  I can confirm that it works correctly with GitHub.
