### ISSUE TITLE
Not working on High Sierra

### ISSUE THREAD

**Issue by edauterman** [github/SoftU2F#38]
I'm using macOS 10.13, and it installed without any errors. I confirmed that the components were installed and the driver is loaded, but when I go to https://demo.yubico.com/u2f?tab=register, I don't see a Chrome notification. I tried running the application from the command line, and I get "Starting softu2f async run loop", but nothing is printed when I try to register a key at the yubico demo site. Interestingly when I try to register at https://u2fdemo.appspot.com/, I see that SoftU2F is sending and receiving frames, but I never actually see a Chrome notification. I've had no problems when using a yubikey.

Any ideas what might be going on?

**Comment by btoews** [comment]
Sorry to hear that you're having trouble. Some more information would help debug this:

- Do you know what version of SoftU2F you downloaded?
- Can you provide the output of `sudo kextstat -b com.github.SoftU2FDriver`
- Can you provide the output of `ps aux | grep -i SoftU2F`

I'm wondering if this has to do with the [new kext loading behavior](https://developer.apple.com/library/content/technotes/tn2459/_index.html) in High Sierra, though it sounds unlikely based on what you've described.

**Comment by edauterman** [comment]
I downloaded the most recent version (v0.0.14). 

The output of `sudo kextstat -b com.github.SoftU2FDriver`:
```
Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
  147    0 0xffffff7f80d82000 0x5000     0x5000     com.github.SoftU2FDriver (1) 2EA38131-DAA2-389A-851A-E6A3ECC90271 <45 5 4 3>
```

The output of `ps aux | grep -i SoftU2F`:
```
emmadauterman    11061   0.0  0.2  4351492  15612   ??  S    10:48AM   0:04.63 /Applications/SoftU2F.app/Contents/MacOS/SoftU2F
emmadauterman    12556   0.0  0.0  4267752   1004 s002  S+    1:29PM   0:00.00 grep -i SoftU2F
```

**Comment by btoews** [comment]
Weird. When you ran it from the command line previously, did you unload the launchagent first (`launchctl unload ~/Library/LaunchAgents/com.github.SoftU2F.plist`)? It shouldn't work to have two instances running simultaneously. 

Do you have any Chrome extensions installed? Maybe try disabling them. Are you on a stable version of Chrome, or nightly? Also, have you tried restarting your system (this is a crappy suggestion, but maybe worth a shot).

Can you maybe copy in the output you are seeing from https://u2fdemo.appspot.com/? For example, I see the following output *before* the notification is ever displayed:

```
$ /Applications/SoftU2F.app/Contents/MacOS/SoftU2F
Starting U2FHID thread
U2FHID thread started
Starting softu2f async run loop.
Received frame:
	CID: 0xffffffff
	TYPE: INIT
	CMD: 0x06
	BCNTH: 0x00
	BCNTL: 0x08
	DATA: 9b 5e 10 ae 88 15 e8 5d 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

Sending frame:
	CID: 0xffffffff
	TYPE: INIT
	CMD: 0x06
	BCNTH: 0x00
	BCNTL: 0x11
	DATA: 9b 5e 10 ae 88 15 e8 5d 01 00 00 00 02 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

Received frame:
	CID: 0x00000001
	TYPE: INIT
	CMD: 0x03
	BCNTH: 0x00
	BCNTL: 0x07
	DATA: 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

Sending frame:
	CID: 0x00000001
	TYPE: INIT
	CMD: 0x03
	BCNTH: 0x00
	BCNTL: 0x08
	DATA: 55 32 46 5f 56 32 90 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

Received frame:
	CID: 0x00000001
	TYPE: INIT
	CMD: 0x03
	BCNTH: 0x00
	BCNTL: 0x49
	DATA: 00 01 03 00 00 00 40 d3 1c cc 5a f5 85 ab c2 50 f5 24 ea b0 9b e3 31 92 40 c0 21 18 77 ad 1b 55 0f 5a 05 23 5a 46 f6 e6 c7 b6 50 dc 34 63 a0 2b b5 0b 29 e7 9d aa 91 4d a9

Received frame:
	CID: 0x00000001
	TYPE: CONT
	SEQ: 0x00
	DATA: f5 56 5d 19 be d9 00 2a 8c 5c bc 77 15 cf 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```

**Comment by edauterman** [comment]
Yep, unloaded the launchagent first. 

I'm running a stable version of Chrome, and I tried restarting just to make sure nothing different was happening. 

The output from https://u2fdemo.appspot.com/ looks very similar to yours (although I never receive a Chrome notification):
```
$ /Applications/SoftU2F.app/Contents/MacOS/SoftU2F
Starting U2FHID thread
U2FHID thread started
Starting softu2f async run loop.
Received frame:
	CID: 0xffffffff
	TYPE: INIT
	CMD: 0x06
	BCNTH: 0x00
	BCNTL: 0x08
	DATA: 30 77 bb 43 df a1 c1 32 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

Sending frame:
	CID: 0xffffffff
	TYPE: INIT
	CMD: 0x06
	BCNTH: 0x00
	BCNTL: 0x11
	DATA: 30 77 bb 43 df a1 c1 32 01 00 00 00 02 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

Received frame:
	CID: 0x00000001
	TYPE: INIT
	CMD: 0x03
	BCNTH: 0x00
	BCNTL: 0x07
	DATA: 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

Sending frame:
	CID: 0x00000001
	TYPE: INIT
	CMD: 0x03
	BCNTH: 0x00
	BCNTL: 0x08
	DATA: 55 32 46 5f 56 32 90 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

Received frame:
	CID: 0x00000001
	TYPE: INIT
	CMD: 0x03
	BCNTH: 0x00
	BCNTL: 0x49
	DATA: 00 01 03 00 00 00 40 cd 56 a9 c1 58 c8 74 73 08 b6 53 78 c7 92 47 2a fd 2c 84 40 90 0a 13 de f0 db e0 5d c5 a5 f1 56 e6 c7 b6 50 dc 34 63 a0 2b b5 0b 29 e7 9d aa 91 4d a9

Received frame:
	CID: 0x00000001
	TYPE: CONT
	SEQ: 0x00
	DATA: f5 56 5d 19 be d9 00 2a 8c 5c bc 77 15 cf 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```

**Comment by btoews** [comment]
What do your notification preferences look like for the SoftU2F app? They should look something like this

![screen shot 2017-10-27 at 3 37 27 pm](https://user-images.githubusercontent.com/1144197/32126233-d1553bfe-bb2c-11e7-9011-927c600f8332.png)

**Comment by edauterman** [comment]
My notification settings look the same!

**Comment by btoews** [comment]
Damn. Is this running on one of the new Macbook Pros with the TouchID bar? Also, are you using an external display? I'm wondering if https://github.com/github/SoftU2F/pull/36 is related.

**Comment by edauterman** [comment]
The external display was causing the problem! I disconnected it and am receiving notifications normally now. Thanks!

**Comment by btoews** [comment]
Weird. The changes in https://github.com/github/SoftU2F/pull/36 should have only affected U2F authentication requests, not registration requests.

**Comment by longrunningprocess** [comment]
fwiw, I just installed it and tested it just fine...

![image](https://user-images.githubusercontent.com/4412848/32915433-d71f0a96-cae6-11e7-9f8e-519017e2c2bb.png)

**Comment by btoews** [comment]
Thanks for the data point @wcjr

**Comment by Manouchehri** [comment]
I've got it running in High Sierra and it seems to work, except for constantly getting this weird error message.

```
mbp:~ dave$ /Applications/SoftU2F.app/Contents/MacOS/SoftU2F --delete-all
Deleted  3  registrations
Error connecting to SoftU2F.kext: -536870203
mbp:~ dave$ /Applications/SoftU2F.app/Contents/MacOS/SoftU2F --show-sep
SEP storage is disabled for new keys
Error connecting to SoftU2F.kext: -536870203
```

**Comment by btoews** [comment]
@Manouchehri That error message is a false alarm. I opened an issue to track fixing this https://github.com/github/SoftU2F/issues/39.

**Comment by btoews** [comment]
I'm going to close this issue, since @evd2014's problem was resolved. I'm still perplexed as to why an external display would cause notifications not to be shown. I regularly use an external display without issue. If others run into this problem we can reopen this.
