### ISSUE TITLE
Prompt is not shown when 1Password asks to save login

### ISSUE THREAD

**Issue by kirinrastogi** [github/SoftU2F#40]
SoftU2F doesn't prompt when 1Password suggests to save the login on demo.yubico.com
I had to kill 1Password Mini, and retry before it prompted.

## System information
macOS High Sierra  10.13.1

#### What browser are you using?
Chrome Version 62.0.3202.94 (Official Build) (64-bit)

#### `sw_vers`
ProductName:	Mac OS X
ProductVersion:	10.13.1
BuildVersion:	17B48

#### `file /Library/Extensions/softu2f.kext /Applications/SoftU2F.app ~/Library/LaunchAgents/com.github.SoftU2F.plist`

/Library/Extensions/softu2f.kext:                                  directory
/Applications/SoftU2F.app:                                         directory
/Users/kirinrastogi/Library/LaunchAgents/com.github.SoftU2F.plist: XML 1.0 document text, ASCII text

#### `kextstat -b com.github.SoftU2FDriver`

Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
  177    0 0xffffff7f83abe000 0x5000     0x5000     com.github.SoftU2FDriver (1) 2EA38131-DAA2-389A-851A-E6A3ECC90271 <48 5 4 3>

#### `ps aux | grep SoftU2F.app`

kirinrastogi     34463   0.0  0.1  4394128  18036   ??  S     5:50pm   0:00.45 /Applications/SoftU2F.app/Contents/MacOS/SoftU2F
kirinrastogi     35116   0.0  0.0  4286200    836 s000  R+    5:59pm   0:00.00 grep SoftU2F.app

#### `grep SoftU2F -a20 -b20 /var/log/install.log | sort -g | uniq | tail -n200`
https://pastebin.com/QE6VrzbT

logs aren't that useful since it looks like it isn't even being called, and I just finished a fresh install of https://github.com/github/SoftU2F/releases/tag/0.0.15-beta3

@mastahyeti 

Looks like 1Password interferes with the protocol... I can't use a yubikey or a u2f zero on the demo site with 1Password mini running...

**Comment by btoews** [comment]
Thanks for opening this. This is related to [this Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=750294). You can find more discussion of this behavior in https://github.com/github/SoftU2F/issues/18. I'm closing this issue since it isn't something that can be addressed in Soft U2F.
