### ISSUE TITLE
Secure Enclave + Touch ID

### ISSUE THREAD

**Issue by ejholmes** [github/SoftU2F#43]
Newer macbooks now feature SEP + Touch ID. Are they any plans to add Touch ID support to this?  The combination of security + usability of a U2F Touch ID implementation would be great. It looks like @btidor has been working on a fork at https://github.com/btidor/u2f-touchid.

**Comment by btoews** [comment]
I added SEP/TouchID support in https://github.com/github/SoftU2F/pull/29. It's currently disabled by default and kind of a beta feature. There's a couple of [command line flags](https://github.com/github/SoftU2F/pull/29#issuecomment-324088826) you can use to enable it.
