### ISSUE TITLE
[Bug] Error connecting to SoftU2F.kext: -536870203

### ISSUE THREAD

**Issue by bartvanvliet** [github/SoftU2F#44]
## System information

To aide in debugging, please provide the output from running the following commands:

#### What browser are you using?

I'm using Chrome

#### `sw_vers`

ProductName:	Mac OS X
ProductVersion:	10.13.2
BuildVersion:	17C88

#### `file /Library/Extensions/softu2f.kext /Applications/SoftU2F.app ~/Library/LaunchAgents/com.github.SoftU2F.plist`

/Library/Extensions/softu2f.kext:                             directory
/Applications/SoftU2F.app:                                    directory
/Users/bvvliet/Library/LaunchAgents/com.github.SoftU2F.plist: XML 1.0 document text, ASCII text

#### `kextstat -b com.github.SoftU2FDriver`

Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
  174    0 0xffffff7f85da8000 0x5000     0x5000     com.github.SoftU2FDriver (1) 8546DC7F-F089-359E-94F0-F23DE3F2866A <48 5 4 3>

#### `ps aux | grep SoftU2F.app`

bvvliet           1566   0.0  0.0  4267768    888 s000  S+    8:16PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn SoftU2F.app
bvvliet           1460   0.0  0.1  4408516  17496   ??  S     8:13PM   0:00.21 /Applications/SoftU2F.app/Contents/MacOS/SoftU2F

#### `grep SoftU2F -a20 -b20 /var/log/install.log | sort -g | uniq | tail -n200`

https://gist.github.com/Kapulara/02544bcee7cfc9345230222e63551449

## Bug

```/Applications/SoftU2F.app/Contents/MacOS/SoftU2F --list```

gives "Error connecting to SoftU2F.kext: -536870203"

```
### 

The following is a list of U2F registrations stored in your keychain. Each key contains several fields:
  - Key handle: This is the key handle that we registered with a website. For Soft U2F, the key handle is simply a hash of the public key.
  - Application parameter: This is the sha256 of the app-id of the site.
  - Known facet: For some sites we know the application parameter → site name mapping.
  - Counter: How many times this registration has been used.
  — In SEP: Whether this registration's private key is stored in the SEP.

Key handle:  QH616tjr6xIqxMSVpwko6AaZtGUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
Application parameter:  VWc7UTjMkNO38yv9rWo4qO3Xs1W3erl5IZbxBtFsoxI=
Known facet:  https://demo.yubico.com
Counter:  1
In SEP:  false

Error connecting to SoftU2F.kext: -536870203
```

**Comment by bartvanvliet** [comment]
Might be because of #39

**Comment by btoews** [comment]
Yep. I'm closing this as a duplicate of https://github.com/github/SoftU2F/issues/39.
