### ISSUE TITLE
SecItemUpdate failing

### ISSUE THREAD

**Issue by btoews** [github/SoftU2F#47]
Apple seems to have broken the `SecItemUpdate` API which is used to store the U2F registration counter. Until this is resolved Soft U2F might not work. I opened a radar with Apple and also an open radar: https://openradar.appspot.com/radar?id=4960969738420224.

**Comment by finansar222** [comment]
grep SoftU2F -a20 -b20 /var/log/install.log | sort -g | uniq | tail -n200
