### ISSUE TITLE
Kernel panic on sending 0x00 buffer

### ISSUE THREAD

**Issue by yackermann** [github/SoftU2F#48]
SoftU2F causes kernel panic if you send it [0x00, 0x00, 0x00, 0x00]. Running v0.0.15

**Comment by btoews** [comment]
Thanks. Where/how were you sending this?

**Comment by yackermann** [comment]
Just been working on some hid project, and by accident sent this buffer to
softu2f

7 мар. 2018 г. 22:55 пользователь "Ben Toews" <notifications@github.com>
написал:
