### ISSUE TITLE
Question: where is the u2f key stored?

### ISSUE THREAD

**Issue by geobio** [github/SoftU2F#52]
Hi, I am hoping to use a single u2f key across my multiple Mac computers. I was trying to find the key in my Keychain, but didn't find anything that looked like a match.

Is there a way to export the key, and move it to other computers, so that I only have a single u2f device registered in my online accounts? For example, my Google account only knows of one u2f device, but I'm able to use SoftU2F on multiple computers?

Thank you!

ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E199

**Comment by btoews** [comment]
The key is stored in your default keychain. Something about the way Soft U2F [generates the keys](https://github.com/github/SoftU2F/blob/master/SoftU2FTool/Keychain.swift#L205-L270) prevents them from being shown in the Keychain.app UI though. I haven't spent much time trying to figure out why this is. There is no easy way to export these keys from the keychain.
