### ISSUE TITLE
OTP support?

### ISSUE THREAD

**Issue by Avinm** [github/SoftU2F#54]
Is it possible to obtain an OTP for the virtual U2F? Some sites require a registration via OTP in order to start using U2F : https://developers.yubico.com/OTP/

**Comment by btoews** [comment]
Thanks for opening an issue. Do you mean Yubico's proprietary OTP, or normal TOPT? What is an example of a service you are trying to register for? Either way, Soft U2F doesn't support any form of OTP. There are many other applications that support regular TOTP though. If you have a mobile phone the [Authy](https://authy.com/) app is a good choice, as it allows you to easily backup your OTP secrets. If you need Yubico OTP, I'm not aware of any software implementation.

**Comment by Avinm** [comment]
Here's more details on the implementation I am talking about: https://developers.yubico.com/OTP/OTPs_Explained.html. Is it possible to implement/generate such an OTP corresponding to the U2F Key generated by SoftU2F?

**Comment by btoews** [comment]
It would be possible to build an application that emulates the Yubico-proprietary OTPs in software, but this feature won't be added to SoftU2F.
