### ISSUE TITLE
Secure Enclave

### ISSUE THREAD

**Issue by hazcod** [github/SoftU2F#60]
Does the current project use the Secure Enclave co-processor in newer macs? (since 2016)

**Comment by btoews** [comment]
Optionally, yes. [Here](https://github.com/github/SoftU2F/pull/29#issuecomment-324088826) are instructions for enabling this feature.

**Comment by acdha** [comment]
Is this feature considered supported enough that it would make sense to update the README to mention it?

**Comment by btoews** [comment]
I still consider that functionality somewhat experimental. It wouldn't hurt to mention it in the README though.

**Comment by philfreo** [comment]
+1! I almost completely dismissed this project when I read:

> A USB authenticator stores key material in hardware, whereas Soft U2F stores its keys in the macOS Keychain.

However if there's a well supported version of this that relies on Touch ID & Secure Enclave then that's definitely worth highlighting!

**Comment by shumink** [comment]
I could’ve missed this project until I clicked on this issue..
