### ISSUE TITLE
Using driver only

### ISSUE THREAD

**Issue by bySabi** [github/SoftU2F#61]
Would it be possible use only the driver part, just like [foohid](https://github.com/unbit/foohid)?

I need create some virtual HID device for test purpose and `foohid` goes outdated.
A generic HID device example will be nice or any indication about.

Regards.

**Comment by btoews** [comment]
It should be possible to only use the driver part. The driver client library ([here](https://github.com/github/SoftU2F/blob/master/SoftU2FDriverLib/softu2f.c)) should be a decent example of how to interact with the driver. I would accept a PR that adds a hello-world example of talking to the driver or documentation on how to use it by itself.
