### ISSUE TITLE
Unable to build and Run from Xcode

### ISSUE THREAD

**Issue by ToruAoyagi** [github/SoftU2F#62]
I want to customize the report descriptor so i tried building and run the source code in X-Code.But i am getting below error when buliding the source code in X-code:

**[default] Unable to load Info.plist exceptions (eGPUOverrides)
SoftU2F.kext not loaded
Error starting Authenticator**

# System information
 Xcode-10.1
 macOS Mojave-10.14.3

**Comment by btoews** [comment]
What target are you trying to run? The error message suggests that you don't have the kernel extension loaded. You need to load that manually in order to run the main `SoftU2F.app` target.

**Comment by btoews** [comment]
Closing as stale.
