### ISSUE TITLE
Windows Port ?

### ISSUE THREAD

**Issue by mcarbonneaux** [github/SoftU2F#63]
They are a port to windows in roadmap ?

**Comment by btoews** [comment]
Nope. This is very specific to macOS. It would be easier to do a total rewrite than to try to port any aspect of this to another platform.

**Comment by 0x326** [comment]
Analogously related to #23 (Linux support)

**Comment by 0x326** [comment]
I know there's a [Swift for Windows](https://swiftforwindows.github.io/) compiler, but I'm not sure how useful it would be since this project might require more features than it supports

**Comment by ibigbug** [comment]
https://github.com/ibigbug/SoftU2F-Win

A rewrite for Windows.
