### ISSUE TITLE
Firefox extension not available

### ISSUE THREAD

**Issue by tnorthcutt** [github/SoftU2F#65]
As of today, the [Firefox extension](https://addons.mozilla.org/en-US/firefox/addon/u2f-support-add-on/) linked in this project's README is unavailable:

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/796639/60196190-d3593300-97f9-11e9-91cd-7eeb05e81b28.png">

**Is there another recommended way to get this to work with Firefox? I'm on version `67.0.4`**

When I try to register on the Yubico demo site, I get this error, after the OS-level prompt for my fingerprint (but before I have time to supply it):

<img width="777" alt="image" src="https://user-images.githubusercontent.com/796639/60196431-61cdb480-97fa-11e9-8958-9abdcc8e5b72.png">

**Comment by CyberFlameGO** [comment]
Hey there! Firefox currently natively supports WebAuthn starting with Firefox 60. I apologize for the late response on this issue.

**Comment by btoews** [comment]
:metal: I just tested this out on latest stable FF
