### ISSUE TITLE
Download page is considered as a deceptive site 

### ISSUE THREAD

**Issue by thagikura** [github/SoftU2F#9]
When I followed the download [link](https://github.com/github/SoftU2F/releases/download/0.0.8/SoftU2F.pkg), Chrome (also Safari reported similarly) reported the site was a deceptive site.

You may need to request a site review for being marked as dangerous.
https://developers.google.com/webmasters/hacked/docs/request_review

Pasted the sentences shown in the download page.

-------------
Deceptive site ahead

Attackers on github-production-release-asset-2e65be.s3.amazonaws.com may trick you into doing something dangerous like installing software or revealing your personal information (for example, passwords, phone numbers, or credit cards).

**Comment by btoews** [comment]
Thanks for opening this. I'll follow those instructions and see if we can get this cleared up.

**Comment by yangwao** [comment]
Looks like it's still there. This is for me major problem, when I recommend it to someone else, there is low chance of using it at all. 
But great thing, keep going! 
![image](https://user-images.githubusercontent.com/5887929/28568692-f5404986-7136-11e7-9339-48487e27e4cd.png)

**Comment by btoews** [comment]
It sounds like this should be resolved. I never got the warning page, so I can't confirm this. Can someone please try again? Thanks.

**Comment by yangwao** [comment]
@mastahyeti works for me now. Downloaded package. 
```
3265818 Jul 25 15:56 SoftU2F.pkg
⫸  shasum -a 512 SoftU2F.pkg
3e626b7eaa6895e89198ce1a3840d925fe69629fd909adbde0018491d4d87b4709283845a446b7fbdeec41992c36461fdf3860e43759241d7b05cea475d2f14a  SoftU2F.pkg
```
Issue about checksum https://github.com/github/SoftU2F/issues/11

**Comment by btoews** [comment]
Thanks for verifying that this is fixed.
